# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('krs', models.IntegerField()),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, null=True)),
            ],
        ),
    ]
