# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20160924_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donator',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
